package com.napontaratan.wifi.model;

import java.util.ArrayList;

import com.google.android.gms.maps.model.LatLng;

/**
 * A simple structure used by the server to plot discovered
 * Wi-Fi connections on the map.
 * 
 * <p>
 * <b>Note:</b> This type is different from <code>WifiConnection</code>,
 * which is used for data generated by clients and sent to the server.
 * WifiMarker on the other hand is generated using a collection of
 * WifiConnection objects. <b>DO NOT DELETE EITHER MODULE.</b>
 * </p>
 * 
 * @see WifiConnection
 * 
 * @author Kurt Ahn
 */
public class WifiMarker {
	/**
	 * 
	 */
    private final ArrayList<WifiRecord> records =
    		new ArrayList<WifiRecord>();
	
	/**
	 * Location of discovery.
	 */
	public final LatLng location;

	/**
	 * 
	 * @param location
	 */
	public WifiMarker(LatLng location) {
		this.location = location;
	}
	
	/**
	 * 
	 * @param record
	 */
	public void addRecord(WifiRecord record) {
		records.add(record);
	}
}
