package com.napontaratan.wifi.model;

import java.sql.Date;

import android.net.wifi.ScanResult;

import com.google.android.gms.maps.model.LatLng;

/**
 * A simple structure generated by clients when Wi-Fi connections
 * are detected.
 * 
 * <p>
 * <b>Note:</b> This type is different from <code>WifiMarker</code>,
 * which is used for data generated by the server and sent to clients
 * for plotting markers where connections are available.
 * <b>DO NOT DELETE EITHER MODULE.</b>
 * </p>
 * 
 * @see WifiMarker
 * 
 * @author Kurt Ahn
 */
public class WifiConnection {
	/**
     * Unique ID of the connection.
     */
	public final String ssid;
	
	/**
	 * Unique ID of the access point.
	 */
	public final String bssid;
	
	/**
	 * Detected signal strength.
	 */
	public final int strength;
	
	/**
	 * Location of discovery.
	 */
	public final LatLng location;
	
	/**
	 * Time of discovery.
	 */
	public final Date date;
	
	/**
	 * Unique ID given to the application's user.
	 */
	public final int clientId;
	
	/*
	 * TODO: We need information about whether the connection is secured, etc.
	 */
	
	/**
	 * Construct a WifiConnection.
	 *
	 * @param scan - Data obtained from scanning for available wifi connections.
	 *        Contains the SSID, BSSID, signal strength, time recorded, etc.
	 * @param location - Location of discovery.
	 * @param date - Date of discovery.
	 * @param clientId - Unique ID given to the application's user.
	 *
	 * @author Kurt Ahn
	 */
	public WifiConnection(
			ScanResult scan, LatLng location, Date date, int clientId) {
		this.ssid = scan.SSID;
		this.bssid = scan.BSSID;
		this.strength = scan.level;
		this.location = location;
		//this.time = scan.timestamp; // This requires min API level of 17
		this.date = date;
		this.clientId = clientId;
	}
	
	/**
	 * @return Information about the connection
	 * 
	 * @author Kurt Ahn
	 */
	@Override
	public String toString() {
		return
			"SSID: " + ssid + "\n" +
			"BSSID: " + bssid + "\n" +
			"Strength: " + String.valueOf(strength) + "\n" +
			"Location: " + location.latitude + " "  + location.longitude + "\n" +
			"Time: " + String.valueOf(date) + "\n" + 
			"Client ID: " + clientId;
	}
}
