package com.napontaratan.wifi.model;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Date;

import android.net.wifi.ScanResult;

import com.google.android.gms.maps.model.LatLng;

/**
 * A simple structure used by the server to plot discovered
 * Wi-Fi connections on the map.
 * 
 * <p>
 * <b>Note:</b> This type is different from <code>WifiConnection</code>,
 * which is used for data generated by clients and sent to the server.
 * WifiMarker on the other hand is generated using a collection of
 * WifiConnection objects. <b>DO NOT DELETE EITHER MODULE.</b>
 * </p>
 * 
 * @see WifiConnection
 * 
 * @author Kurt Ahn
 */
public class WifiMarker {
    /**
     * Unique ID of the connection.
     */
	private final String ssid;
	
	/**
	 * Unique ID of the access point.
	 */
	private final String bssid;
	
	/**
	 * Location of discovery.
	 */
	private final LatLng location;
	
	
	// What's the point of having getters for final fields?
	// Can't we just make the fields public?
	// ==== getters ====
	public String getSSID() {
		return ssid;
	}

	public String getBSSID() {
		return bssid;
	}

	public LatLng getLocation() {
		return location;
	}

	public WifiMarker(String ssid, String bssid, LatLng location) {
		// Temporary stuff
		this.ssid = ssid;
		this.bssid = bssid;
		this.location = location;
	}
	
	
}
